# Generated by Django 4.2.7 on 2023-11-23 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_userconfirmcode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userconfirmcode",
            old_name="confirm_code",
            new_name="code",
        ),
        migrations.AlterField(
            model_name="userconfirmcode",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="confirm_code",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
